volumes:
  server_node_modules:
  client_node_modules:
  db_data:
  ollama:
services:
  db:
    image: postgres:latest
    container_name: db
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build:
      context: ./server
    container_name: server
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      - db

  client:
    build:
      context: ./client
    container_name: client
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    ports:
      - "5173:5173"

  ollama:
        image: ollama/ollama:latest
        container_name: ollama
        ports:
          - "11434:11434"
        volumes:
          - ollama:/root/.ollama

  # worker:
  #   build:
  #     context: ./server
  #   container_name: ollama_demo_server
  #   volumes:
  #     - ./worker:/app
  #     - ./prisma:/app/prisma
  #     - server_node_modules:/app/node_modules
  #   ports:
  #     - "3001:3001"
  #   env_file:
  #     - ./server/.env
  #   depends_on:
  #     - db
  #     - cache
